name = "GregTech Leisure"
author = "kairan0"
version = "1.4.5.1-kairan.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f95871c448121b926eef35d72196e6719f777949cf540c1317465ec669765a5e"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
