name = "GregTech Leisure"
author = "kairan0"
version = "1.4.5.1-kairan.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f5bc109f7c8e6d30720f773e173d712335f4a8d8cbc8486ea57c54391cc115e"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
