name = "GregTech Leisure"
author = "kairan0"
version = "1.4.5.1-kairan.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "841c4b8a2043be02141e1160f60f55d673fb8f6592c174c65ee88742132d77d1"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
