#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Sep 07 00:13:43 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=ComplementaryUnbound_r5.6.1.zip
enableShaders=false
